# Generated by Django 3.1 on 2020-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(choices=[('BA', 'BA'), ('BASC', 'BASC'), ('BCOM', 'BCOM'), ('BSC', 'BSC'), ('other', 'other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('5th year', '5th year'), ('other', 'other')], default='', max_length=10),
        ),
    ]
