# Generated by Django 3.1 on 2020-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200914_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(choices=[('', 'Select Specialization'), ('BA', 'BA'), ('BASC', 'BASC'), ('BCOM', 'BCOM'), ('BSC', 'BSC'), ('other', 'other')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('', 'Select Year'), ('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('5th year', '5th year'), ('other', 'other')], default='select', max_length=10),
        ),
    ]
