# Generated by Django 3.1 on 2020-09-13 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200827_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('link', models.TextField(max_length=150)),
                ('participants', models.ManyToManyField(related_name='users_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
