# Generated by Django 3.1 on 2020-09-14 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200914_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideathon',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
