# Generated by Django 3.1 on 2020-09-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ideathon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideathon',
            name='Summary',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
